version: '3'

services:
  cache:
    image: redis
    restart: always
    env_file:
      - .env
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  bot:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: >
      sh -c "sleep 4
      && alembic upgrade head
      && python3 bot.py"
volumes:
  db: